version: '3.9'

services:
  api:
    build: ./api
    container_name: senadores_api
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: senadores_frontend
    ports:
      - "5173:5173"
